tasks:
  - name: aws-cli
    env:
      AWS_CLI_AUTO_PROMPT: on-partial
    init: |
      cd /workspace
      curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      unzip awscliv2.zip
      sudo ./aws/install
      cd $THEIA_WORKSPACE_ROOT
      
      gp env AWS_ACCESS_KEY_ID=""
      gp env AWS_SECRET_ACCESS_KEY=""
      gp env AWS_DEFAULT_REGION=eu-west-1
      
      export AWS_ACCESS_KEY_ID=""
      export AWS_SECRET_ACCESS_KEY=""
      export AWS_DEFAULT_REGION=eu-west-1
vscode:
  extensions:
    - 42Crunch.vscode-openapi


