tasks:
  - name: aws-cli
    env:
      AWS_CLI_AUTO_PROMPT: on-partial
    init: |
      cd /workspace
      curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      unzip awscliv2.zip
      sudo ./aws/install
      cd $THEIA_WORKSPACE_ROOT
vscode:
  extensions:
    - 42Crunch.vscode-openapi

gp env AWS_ACCESS_KEY_ID="AKIAZDGU3MDQEIP2Q6UX"
gp env AWS_SECRET_ACCESS_KEY="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"
gp env AWS_DEFAULT_REGION=eu-west-1

export AWS_ACCESS_KEY_ID="AKIAZDGU3MDQEIP2Q6UX"
export AWS_SECRET_ACCESS_KEY="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"
export AWS_DEFAULT_REGION=eu-west-1



